CREATE TABLE BANK_ACCOUNT (
   ACCOUNT_ID INTEGER NOT NULL,
   ACCOUNT_TYPE VARCHAR(50) NOT NULL,
   BALANCE INTEGER NOT NULL,
   PRIMARY KEY (ACCOUNT_ID));

CREATE TABLE CUSTOMERS (
   CUSTOMER_ID INTEGER NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   ADDRESS VARCHAR(100) NOT NULL,
   ACCOUNT_ID INTEGER NOT NULL,
   PRIMARY KEY (CUSTOMER_ID));

CREATE TABLE ACCOUNT_DETAILS (
   ACCOUNT_TYPE VARCHAR(50) NOT NULL,
   INTEREST INTEGER NOT NULL,
   PRIMARY KEY (ACCOUNT_TYPE));

-- PARTITION TABLE BANK_ACCOUNT ON COLUMN ACCOUNT_ID;
   
-- CREATE PROCEDURE FROM CLASS UpdateBalance;
 
 -- Partition declarations for the Stored Procedures:
 -- PARTITION PROCEDURE <ProcedureName> ON TABLE <TABLE NAME> COLUMN <Partitioning Column>;
 
